// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  'aws_project_region': 'eu-central-1',
  'aws_cognito_identity_pool_id': 'eu-central-1:02352d66-9cdc-4ba2-a6b8-3df0ae823e3d',
  'aws_cognito_region': 'eu-central-1',
  'aws_user_pools_id': 'eu-central-1_NIhuQ8gNK',
  'aws_user_pools_web_client_id': '2opeadrmn73u4dv287rfolaq18',
  'aws_appsync_authenticationType': 'AMAZON_COGNITO_USER_POOLS'
};


export default awsmobile;
